apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: webserver
    tier: backend
spec:
  containers:
  - name: webapp
    image: zxcvbnius/docker-demo
    ports:
    - containerPort: 3000

