apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  ports:
  - port: 3000
    nodePort: 30390
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress-deployment
  type: NodePort

